### ISSUE TITLE
Fix card / state / transition bugs

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#257]
<a href="https://github.com/toddmedema"><img src="https://avatars2.githubusercontent.com/u/775657?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [toddmedema](https://github.com/toddmedema)**
_Monday May 28, 2018 at 17:58 GMT_
_Originally opened as https://github.com/ExpeditionRPG/expedition-app/issues/713 (0 comment(s))_

----

1. Removing the card_transitioning action cleaned up a lot of stuff, but it means that cards once again re-draw right before they slide away. I believe @smartin015 found a promising alternative along the lines of hooking into a willLeave / hasLeft lifecycle event
2. Also seeing a bug where going back doesn't consistently / fully reset the store. For example, open a quest, go back, and then open tools and suddenly the quest is back in the store! (you can tell because the URL once again has the quest ID in the hash)

**Comment by smartin015** [comment]
1. I think this is obsolete... 

2. I have a fix in for this - turns out it's not the fault of history logic, rather it's because we're updating the quest state (via PREVIEW_QUEST) and then dispatching toCard, which snapshots the store before transitioning. In that world, we pop off the state after PREVIEW_QUEST was called and the quest state is preserved.

**Comment by smartin015** [comment]
Aaaand I accidentally pushed straight to master :(

https://github.com/ExpeditionRPG/expedition/commit/a8697d60bb962b645976e7e515aa2f817dee9c25

BRB, fixing push permissions controls...

**Comment by toddmedema** [comment]
(to clarify, are you setting it to block master pushes?)
