### ISSUE TITLE
QDL op improvement: don't break / error on undefined vars

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#421]
This particular issue causes so many errors that it basically makes Sentry error reporting useless - and also creates a very bad user impression to see so many errors appear. This is especially prevalent in [Kingdom of Kelendia](https://quests.expeditiongame.com/#1IQ680ia9CijWx_ooFM5KtWCyeov2unpn)

Here's what happens: an author uses a line like `{{B_Playing==true ? "The Befuddled Mage, " : "The bedraggled young man, "}}`, except that the players have somehow played through a route in the quest where `B_Playing` never gets defined. 

I see two options:

1. Figure out how to make MathJS not throw a fit when referencing a variable that isn't defined. The main downside I can think of is that this may cause unexpected behavior if players go down a path where the variable is undefined but the author expected it to be defined. However, even if we have the below improvement made to the quest creator, I still believe this would be a valuable improvement to make to the app to make it more robust for / show fewer errors to users.
2. Improve Quest Creator crawling to identify and error on paths where a variable is reference before it's defined, which in general would improve the quality of *future* quests written. However, I expect this to be more engineering work & detection to still be flawed given that it's impossible to guarantee crawling a quest to completion.

@smartin015 thoughts?

**Comment by smartin015** [comment]
Re #2, I thought this was what the quest crawler already did, but clearly it doesn't - this is a bug IMO. Crawling should at least pick up most of these instances, at which point it shouldn't be that big of a problem overall. 

Catching MathJS errors and handling them silently would probably cause people to think the quest was bad, rather than buggy. Maybe that's a better experience.

Perhaps we should go ahead with both?
