### ISSUE TITLE
Quest Creator Emulated Client Issues

### ISSUE THREAD

**Issue by jamesabowling** [ExpeditionRPG/expedition#481]
Two issues are not present in the iOS mobile app but exist in the "Play from cursor" function in the Quest Creator (tested  using Chrome 69.0.3497.100 64-bit).

1. This RNG function always returns the value "20" instead of a random number between1 and 20:  {{houseroll1 = floor(random() * 20) + 1}}
2. Cards near the end of a quest cause the Quest Creator to crash with the error: "TypeError: Cannot read property 'length' of undefined" when I click "Play from cursor".  (example quest ID 1XCwYD_IYkMI_uOn4eKcPXx2lVl75moCx with cursor on line 837).

**Comment by toddmedema** [comment]
@jamesabowling 2 actually turned out to be a different issue - you had `{{_.randomEnemyOfClassTier("Bandit", 1)}}`, but the bandit needed to be lowercase. Fixed in your quest, and opened a pull request to fix the requirement that the capitalization match perfectly - https://github.com/ExpeditionRPG/expedition/pull/485

**Comment by toddmedema** [comment]
Fix will be deployed within the hour!
