### ISSUE TITLE
Private quests appearing that aren't mine?

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#585]
They correctly go away when "show my private quests" is unchecked, but they definitely aren't mine (just to make sure they aren't quests I forgot about from a long time ago, I filtered on quests published in the last month)
<img width="258" alt="screen shot 2018-12-08 at 5 24 24 pm" src="https://user-images.githubusercontent.com/775657/49691352-209bde80-fb0e-11e8-9ab8-8fc93bf7bd14.png">

**Comment by smartin015** [comment]
Rolled back to version 330, appears to have mitigated this.

Looks like it was caused by a PR 11 days ago: https://github.com/ExpeditionRPG/expedition/blame/master/services/api/src/models/Quests.ts#L64

Remaining effort needed:
- [ ] Fix the problem in master
- [ ] Add regression tests to make sure other users' private quests are never shown.
- [ ] Add "check nobody else's private quests showing up" as an explicit thing to verify in QA

**Comment by smartin015** [comment]
![image](https://user-images.githubusercontent.com/607666/49699124-5509ac00-fb9b-11e8-9972-53bae124af0e.png)
