### ISSUE TITLE
Combat on round errors when no next goto

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#638]
Blocking publishing Mistress Malaise - https://quests.expeditiongame.com/#0BzrQOdaJcH9MWTRBNmNXT1d2UkU

(which is also blocking us publishing a public version of Mistress Malaise that is marked as "Official" - so, at the moment, Mistress Malaise is not available to logged in users)

**Comment by smartin015** [comment]
Fixed the error on MM by adding an `**end**` tag at the bottom of the quest, working now to add an exception in the crawler. The error occurs only when all of the following hold:

1. there's a combat node at the very end of a quest, with no nodes after it
2. the combat node uses `* on round`
3. the "on round" flow has at least one branching path that does not end in a trigger

Since this is pretty specific and we have a workaround, I'm lowering the impact on this bug.

**Comment by toddmedema** [comment]
Re-opening as it looks like this is not fully fixed in the latest quest creator deploy - just try playing through Mistress Malaise as linked. Without an extra `**end**` added to the end of the quest, the crawler throws an error. With that end added, any choice that does not end in a trigger ends the quest / falls out of combat. The correct behavior should be to stay in combat / loop into the next round.
