### ISSUE TITLE
LTP quest: Make the market choice meaningful

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#750]
Creates a bad first impression of the Expedition system if the first choice you make doesn't matter

**Comment by sciorms** [comment]
@toddmedema  I have some thoughts regarding this issue that could be useful to talk about before I submit a PR against this issue. After reviewing the intro quest's xml, I see two things that can be easily change to add more impact to this encounter:

1) There are three branches during the market scene of the quest but two of the branches are basically identical with slightly different flavor text. I think an easy way to handle this would be to only show two options on "The Market" scene which are either attempt to intimidate the faeries verbally or use force to subdue them and then transition from "Intimidation Tactics"  or "Force" to "Attempted Arrest". The "Attempted Arrest" scene may need to be modified as well based on the success of either branch. 

2) There seems to be no way to actually intimidate the faeries in the market. I think you could add a roll prompt here where a 15+ successfully intimidates them and they surrender peacefully. I believe a 15+ would be a good roll because new guards would not have tons of influence within the town but they may have some minimal influence because they are guards nonetheless. If this roll fails then the fairies attack the group and start combat.

If you think this is a good potential solution I could write this up and submit a PR for it. Let me know what your thoughts are.

**Comment by toddmedema** [comment]
That sounds reasonable! I will say, the reason we did that is that the LTP needs combat to teach you about combat - so maybe the intimidation still has combat, but makes it easier? (and lets the user know that it's easier, i.e. you deal +1 damage this combat because you intimidated them)

**Comment by sciorms** [comment]
@toddmedema this can probably be marked as fixed per PR #839
