### ISSUE TITLE
Allow disabling Persona

### ISSUE THREAD

**Issue by joecot** [ExpeditionRPG/expedition#774]
Consider this either in addition to or instead of #762

Allow disabling the use of Persona. This can be done on either:
* The settings page in the app (I expect this is easier)
* Adding a checkbox to the quest setup page at the beginning of the quest.

If this option is enabled:

* On quest Setup page:
    * Personas
        * If using Horror: Instruct not to pick a persona
        * If using Horror + Future: Instruct to pick a persona, but not place a tracker on it. Will only be used for Light or Dark for skill checks. Alternatively can just remove Light/Dark from skill checks if that's implemented as part of #762, and then can instruct not to pick a Persona.
    * Instruct to Pick Adventurers which do not have Influence powers. Alternatively, the group can decide which other Power type the Adventurer receives.
    * Instruct not to take influence cards
    * Instruct to Ignore Quest actions which affect Persona (if these screens can't be removed in an automated way)
    * Instruct: If a player draws a loot card which affects Persona, discard and pick a new loot card.
    * Instruct: If a creature's surge effect involves losing Persona, instead take an additional damage at end of round (or whatever alt effect seems reasonable).
* On Combat Surge page: Reiterate alternate surge effect for creature effects involving Persona
* When giving loot items: Reiterate discarding and redrawing Loot items with Persona effects.

**Comment by toddmedema** [comment]
Thank you for the detailed submission! It'll be easier and safer for us to support disabling the whole Horror expansion, so I've merged your thoughts into the other ticker #762 

(Why that is: the codebase doesn't currently support toggling individual mechanics, just whole expansions, so we'd likely induce a lot of new bugs. Additionally, since all cards in The Horror integrate with the Persona mechanic, it'd be a pretty clunky play experience to play with everything in the Horror except Persona)
